company: Toyota
description: Renode support for STM32L552 for the [RAMN platform](https://github.com/ToyotaInfoTech/RAMN).
name: Toyota RAMN (GH version)
spec: ./specification.json
scenarios:
  RAMN Device with PC:
    device: ramn_device_with_pc
    payloads:
      - device: ramn_device -> ramn -> stmicroelectronics-stm32l552cct6--0
        software: ramn_firmware
      - device: ramn_device -> ramn -> stmicroelectronics-stm32l552cct6--1
        software: ramn_firmware
      - device: ramn_device -> ramn -> stmicroelectronics-stm32l552cct6--2
        software: ramn_firmware
      - device: ramn_device -> ramn -> stmicroelectronics-stm32l552cct6--3
        software: ramn_firmware
      - software: carla
        device: carla_control_pc
devices:
  RAMN:
    category: Boards
    contains:
      - stmicroelectronics-stm32l552cct6
      - stmicroelectronics-stm32l552cct6
      - stmicroelectronics-stm32l552cct6
      - stmicroelectronics-stm32l552cct6
      - microchip-technology-ata6561-gaqw-n
      - microchip-technology-ata6561-gaqw-n
      - microchip-technology-ata6561-gaqw-n
      - microchip-technology-ata6561-gaqw-n
    sources:
      HW design (main): $GH/ToyotaInfoTech/RAMN:hardware/V1_revB/0_ramn
  RAMN screens:
    category: Boards
    sources:
      HW design (main): $GH/ToyotaInfoTech/RAMN:hardware/V1_revB/1_screens
  RAMN chassis:
    category: Boards
    sources:
      HW design (main): $GH/ToyotaInfoTech/RAMN:hardware/V1_revB/2_chassis
  RAMN powertrain:
    category: Boards
    sources:
      HW design (main): $GH/ToyotaInfoTech/RAMN:hardware/V1_revB/3_powertrain
  RAMN body:
    category: Boards
    sources:
      HW design (main): $GH/ToyotaInfoTech/RAMN:hardware/V1_revB/4_body
  RAMN debugger:
    category: Boards
    sources:
      HW design (main): $GH/ToyotaInfoTech/RAMN:hardware/V1_revB/5_debugger
  RAMN Device:
    description: "RAMN (Resistant Automotive Miniature Network) is a miniature CAN/CAN-FD testbed of four Electronic Control Units (ECUs). The ECUs can be programmed to emulate the same network traffic as PASTA. RAMN is powered over USB and can be recognized as a standard CAN adapter. It can be connected in closed-loop with the autonomous driving simulator CARLA"
    category: Complex devices
    contains:
      - ramn
      - ramn_screens
      - ramn_body
      - ramn_chassis
      - ramn_powertrain
      - adafruit-4313
  CARLA Control PC:
    description: PC used to run the CARLA simulator
  RAMN Device with PC:
    category: Complex devices
    contains:
      - RAMN Device
      - CARLA Control PC
software:
  RAMN firmware:
    description: "STM32 Cube project containing firmware for RAMN (Resistant Automotive Miniature Network) Electronic Control Units (ECUs) "
    what: bare-metal-firmware
    sources:
      GitHub: $GH/ToyotaInfoTech/RAMN@main:firmware
  CARLA:
    description: "Open-source simulator for autonomous driving research"
    what: linux-app
    sources:
      GitHub: $GH/carla-simulator/carla@ue5-dev
  PASTA:
    description: "Portable Automotive Security Testbed with Adaptability - a platform based on non-proprietary technology, allowing researchers or engineers to freely construct in-vehicle networks"
    what: bare-metal-firmware
    sources:
      GitHub: $GH/pasta-auto/PASTA1.0@master
